PrjCinemaTest.MVC/Controllers/ConfiguracaoGrupoUsuarioPermissaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using PrjCinema.Domain.Entities;
using PrjCinema.Domain.Entities.Permissoes;
using PrjCinema.Domain.Interfaces.Service;
using PrjCinema.MVC.Models;
using PrjCinema.Service.Service;

namespace PrjCinema.MVC.Controllers
{
    public class ConfiguracaoGrupoUsuarioPermissaoController : Controller
    {
        private readonly IGrupoAcessoService _grupoAcessoService;
        private readonly IPermissaoService _permissaoService;
        private readonly IOperacaoService _operacaoService;
        private readonly IUsuarioService _usuarioService;
        private readonly ITelaService _telaService;
        private readonly UsuarioService __usuarioService;
        private readonly PermissaoService __permissaoService;
        public ConfiguracaoGrupoUsuarioPermissaoController(UsuarioService usuarioService, TelaService telaService, GrupoAcessoService grupoAcessoService, PermissaoService permissaoService, OperacaoService operacaoService)
        {
            __permissaoService = permissaoService;
            __usuarioService = usuarioService;
            _operacaoService = operacaoService;
            _telaService = telaService;
            _usuarioService = usuarioService;
            _grupoAcessoService = grupoAcessoService;
            _permissaoService = permissaoService;
        }

        //-------------------------------Permissões------------------------------------------

        //GET: ConfiguracaoGrupoUsuarioPermissao
        public ActionResult IndexPermissoes()
        {
            return View(Mapper.Map<IEnumerable<Permissao>, IEnumerable<PermissaoModelView>>(_permissaoService.GetAll()));
        }

        // GET: ConfiguracaoGrupoUsuarioPermissao/Details/5
        public ActionResult DetailsPermissao(int id)
        {
            return View(Mapper.Map<Permissao, PermissaoModelView>(_permissaoService.GetById(id)));
        }

        // GET: ConfiguracaoGrupoUsuarioPermissao/Create
        public ActionResult CreatePermissao()
        {
            ViewBag.Telas = Mapper.Map<IEnumerable<Tela>, ICollection<TelaModelView>>(_telaService.GetAll());
            ViewBag.Operacoes = Mapper.Map<IEnumerable<Operacao>, ICollection<OperacaoModelView>>(_operacaoService.GetAll());
            return View();
        }

        // POST: ConfiguracaoGrupoUsuarioPermissao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePermissao(PermissaoModelView permissaoModelView, int[] operacaoId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var permissao = Mapper.Map<PermissaoModelView, Permissao>(permissaoModelView);
                    foreach (var op in operacaoId)
                    {
                        permissao.Operacoes.Add(_operacaoService.GetById(op));
                    }
                    _permissaoService.Add(permissao);
                    return RedirectToAction("IndexPermissoes");
                }

                return RedirectToAction("CreatePermissao", permissaoModelView);

            }
            catch (Exception e)
            {
                ViewBag.Erro = e.Message;
                return View(permissaoModelView);
            }
        }

        // GET: Permissao/Edit/5
        public ActionResult EditPermissao(int id)
        {
            ViewBag.Telas = Mapper.Map<IEnumerable<Tela>, ICollection<TelaModelView>>(_telaService.GetAll());
            return View(Mapper.Map<Permissao, PermissaoModelView>(_permissaoService.GetById(id)));
        }

        // POST: Permissao/Edit/5
        [HttpPost]
        public ActionResult EditPermissao(PermissaoModelView permissao, int telaId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    permissao.Tela = _telaService.GetById(telaId);
                    permissao.TelaId = telaId;
                    _permissaoService.Update(Mapper.Map<PermissaoModelView, Permissao>(permissao));
                    return RedirectToAction("IndexPermissoes");
                }
                return RedirectToAction("EditPermissao", permissao);
            }
            catch (Exception e)
            {
                ViewBag.Erro = e.Message;
                return View(permissao);
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult AddOpercaoAPermissao(int id)
        {
            ViewBag.Operacoes = Mapper.Map<IEnumerable<Operacao>, ICollection<OperacaoModelView>>(_operacaoService.GetAll());
            return View(Mapper.Map<Permissao, PermissaoModelView>(_permissaoService.GetById(id)));
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult AddOpercaoAPermissao(PermissaoModelView permissao, int operacaoId)
        {
            var getPermissaoComObjCorreto = _permissaoService.GetById(permissao.Id);
            try
            {
                if (ModelState.IsValid)
                {
                    getPermissaoComObjCorreto.Operacoes.Add(_operacaoService.GetById(operacaoId));
                    _permissaoService.Update(getPermissaoComObjCorreto);
                    return RedirectToAction("IndexPermissoes");
                }
                return RedirectToAction("CreateGrupoAcesso");
            }
            catch (Exception E)
            {
                ViewBag.Erro = E.Message;
                ViewBag.Operacoes = _operacaoService.GetAll();
                return View(Mapper.Map<Permissao, PermissaoModelView>(getPermissaoComObjCorreto));
            }
        }

        //-------------------------------Grupo de Acesso------------------------------------------

        public ActionResult IndexGrupoAcessos()
        {
            return View(Mapper.Map<IEnumerable<GrupoAcesso>, IEnumerable<GrupoAcessoModelView>>(_grupoAcessoService.GetAll()));
        }

        // GET: Usuario/Edit/5
        public ActionResult AddPermissaoAoGrupoAcesso(int id)
        {
           ViewBag.Permissoes = Mapper.Map<IEnumerable<Permissao>, ICollection<PermissaoModelView>>(__permissaoService.GetPermissoesFaltantesNoGrupo(id));
            return View(Mapper.Map<GrupoAcesso, GrupoAcessoModelView>(_grupoAcessoService.GetById(id)));
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult AddPermissaoAoGrupoAcesso(GrupoAcessoModelView grupoAcesso, int permissaoId)
        {
            var getGrupoAcessoComObjCorreto = _grupoAcessoService.GetById(grupoAcesso.Id);
            try
            {
                if (!ModelState.IsValid)
                {

                    var idVindoDoViewBagDaPermissao = _permissaoService.GetById(permissaoId);
                    if (getGrupoAcessoComObjCorreto.Permissoes.Any(u => u.Tela == idVindoDoViewBagDaPermissao.Tela))
                    {
                        throw new Exception("Este grupo já possui uma permissão com acesso de Tela. Caso necessário consulte seu Administrador !");
                    }
                    getGrupoAcessoComObjCorreto.Permissoes.Add(idVindoDoViewBagDaPermissao);
                    _grupoAcessoService.Update(getGrupoAcessoComObjCorreto);
                    return RedirectToAction("IndexGrupoAcessos");
                }
                return RedirectToAction("CreateGrupoAcesso");
            }
            catch (Exception E)
            {
                ViewBag.Erro = E.Message;
                ViewBag.Usuarios = Mapper.Map<ICollection<Usuario>, ICollection<UsuarioModelView>>(_usuarioService.GetAll());
                return View(Mapper.Map<GrupoAcesso, GrupoAcessoModelView>(getGrupoAcessoComObjCorreto));
            }
        }

        // GET: Usuario/Edit/5
        public ActionResult AddUsuarioAoGrupoAcesso(int id)
        {
            ViewBag.Usuarios = Mapper.Map<IEnumerable<Usuario>, ICollection<UsuarioModelView>>(__usuarioService.GetUsuariosFaltantesNoGrupo(id));
            return View(Mapper.Map<GrupoAcesso, GrupoAcessoModelView>(_grupoAcessoService.GetById(id)));
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        public ActionResult AddUsuarioAoGrupoAcesso(GrupoAcessoModelView grupoAcesso, int usuarioId)
        {
            var getGrupoAcessoComObjCorreto = _grupoAcessoService.GetById(grupoAcesso.Id);
            try
            {
                if (!ModelState.IsValid)
                {

                    var idVindoDoViewBagDaUsuario = _usuarioService.GetById(usuarioId);
                    getGrupoAcessoComObjCorreto.Usuarios.Add(idVindoDoViewBagDaUsuario);
                    _grupoAcessoService.Update(getGrupoAcessoComObjCorreto);
                    return RedirectToAction("IndexGrupoAcessos");
                }
                return RedirectToAction("CreateGrupoAcesso");
            }
            catch (Exception E)
            {
                ViewBag.Erro = E.Message;
                ViewBag.Usuarioes = Mapper.Map<ICollection<Usuario>, ICollection<UsuarioModelView>>(_usuarioService.GetAll());
                return View(Mapper.Map<GrupoAcesso, GrupoAcessoModelView>(getGrupoAcessoComObjCorreto));
            }
        }

        // GET: ConfiguracaoGrupoUsuarioPermissao/Details/5
        public ActionResult DetailsGrupoAcesso(int id)
        {
            ViewBag.Usuarios = __usuarioService.BuscaUsuariosPorGrupoAcesso(id);
            ViewBag.Permissoes = __permissaoService.BuscaPermissoesPorGrupoAcesso(id);
            return View(Mapper.Map<GrupoAcesso, GrupoAcessoModelView>(_grupoAcessoService.GetById(id)));
        }

        // GET: ConfiguracaoGrupoUsuarioPermissao/Create
        public ActionResult CreateGrupoAcesso()
        {
            ViewBag.Permissoes = _permissaoService.GetAll();
            return View();
        }

        // POST: ConfiguracaoGrupoUsuarioPermissao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

PrjCinemaTest.MVC/Views/Shared/_InfoUsuario.cshtml
@using PrjCinema.Domain.Entities
@{
    Usuario usu = (Usuario)Session["UsuarioLogado"];
}

<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Usúario Logado
        <span class="caret"></span></button>
    <ul class="dropdown-menu">
        <li><b> Nome: </b><label class="control-label">@usu.Nome</label><span class="sr-only">(success)</span></li>
        <li><b> Email: </b><label class="control-label">@usu.Email</label><span class="sr-only">(success)</span></li>
        <li><b> Cpf: </b><label class="control-label">@usu.Cpf</label><span class="sr-only">(success)</span></li>
        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
    </ul>
</div>

@*<div class="form-group has-success has-feedback">


</div>*@

PrjCinemaTest.MVC/Views/Shared/_Layout.cshtml
@using PrjCinema.MVC.Util
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["UsuarioLogado"] != null)
            {
                    @Html.ActionLink("Seriando App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Seriando App", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["UsuarioLogado"] != null)
                    {
                        if (ULogin.IsPermiteTela("Usuario"))
                        {
                            <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
                        }
                        if (ULogin.IsPermiteTela("GrupoAcesso"))
                        {
                            <li>@Html.ActionLink("Grupos de Acesso", "IndexGrupoAcessos", "ConfiguracaoGrupoUsuarioPermissao")</li>
                        }
                        if (ULogin.IsPermiteTela("Permissao"))
                        {
                            <li>@Html.ActionLink("Permissões", "IndexPermissoes", "ConfiguracaoGrupoUsuarioPermissao")</li>
                        }
                        if (ULogin.IsPermiteTela("Filme"))
                        {
                            <li>@Html.ActionLink("Filmes", "Index", "Filme")</li>
                        }
                        if (ULogin.IsPermiteTela("Serie"))
                        {
                            <li>@Html.ActionLink("Series", "Index", "Serie")</li>
                        }
                        if (ULogin.IsPermiteTela("Ator"))
                        {
                            <li>@Html.ActionLink("Atores", "Index", "Ator")</li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["UsuarioLogado"] != null)
                    {
                        @Html.Partial("_InfoUsuario")
                        @ViewBag.UsuarioLogin
                    }
                </ul>

                <input type="hidden" id="success"
                       value="@TempData["success"]" />
                <input type="hidden" id="info"
                       value="@TempData["info"]" />
                <input type="hidden" id="warning"
                       value="@TempData["warning"]" />
                <input type="hidden" id="error"
                       value="@TempData["error"]" />
            </div>
        </div>


    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="card-img-top">
            <p>&copy; @DateTime.Now.Year - Aplicação de teste</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquerymascara")
    @Scripts.Render("~/bundles/toast")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/Content/datatables")
    @RenderSection("scripts", required: false)
</body>
</html>